swagger: "2.0"
info:
  description: "Here is description."
  version: "1.0.0"
  title: "Web API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "test@test.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /some/{id}:
    get:
      summary: "Some information"
      description: "You can get some information via this api."
      parameters:
        - name: "id"
          in: "path"
          description: "Some ID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "this is value string."
